---
abstract: 'A POE based SOCKS 4 proxy server.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Proxy-SOCKS
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::Proxy::SOCKS:
    file: lib/POE/Component/Proxy/SOCKS.pm
    version: 1.02
requires:
  Net::Netmask: 1.9015
  POE: 1.28
  POE::Component::Client::DNS: 0.99
  POE::Component::Client::Ident: 1.03
  POE::Filter::Stream: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-proxy-socks/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-proxy-socks.git
version: 1.02
