author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Component-Proxy-SOCKS
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Net::Netmask: 1.9015
  POE: 0.38
  POE::Component::Client::DNS: 0.99
  POE::Component::Client::Ident: 1.03
  Socket: 0
version: 0.02
